sudo rm -rf /tmp/storage/
docker login docker.flsim.iovi.com:5000
docker pull docker.flsim.iovi.com:5000/flsim-env:0.2.2
docker pull docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00001 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00001" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00009 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00009" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00010 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00010" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00011 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00011" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00013 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00013" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00021 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00021" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00025 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00025" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00026 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00026" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00027 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00027" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00029 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00029" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00030 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00030" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00031 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00031" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00034 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00034" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00035 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00035" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00036 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00036" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00039 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00039" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00046 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00046" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00047 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00047" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00052 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00052" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00053 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00053" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00058 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00058" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00060 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00060" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00071 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00071" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00075 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00075" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00077 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00077" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00079 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00079" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00081 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00081" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00084 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00084" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00085 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00085" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00087 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00087" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00088 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00088" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00089 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00089" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00090 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00090" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00092 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00092" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00093 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00093" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00097 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00097" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00098 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00098" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8