sudo rm -rf /tmp/storage/
docker login docker.flsim.iovi.com:5000
docker pull docker.flsim.iovi.com:5000/flsim-env:0.2.2
docker pull docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00004 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00004" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00005 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00005" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00015 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00015" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00016 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00016" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00018 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00018" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00024 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00024" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00028 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00028" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00037 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00037" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00040 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00040" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00049 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00049" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00056 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00056" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00057 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00057" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00065 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00065" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00069 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00069" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00078 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00078" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00091 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00091" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00094 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00094" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00095 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00095" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00096 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00096" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00099 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00099" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8