sudo rm -rf /tmp/storage/
docker login docker.flsim.iovi.com:5000
docker pull docker.flsim.iovi.com:5000/flsim-env:0.2.2
docker pull docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00003 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00003" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00006 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00006" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00020 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00020" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00023 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00023" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00032 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00032" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00038 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00038" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00044 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00044" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00050 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00050" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00054 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00054" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00055 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00055" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00059 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00059" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00061 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00061" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00062 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00062" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00063 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00063" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00064 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00064" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00066 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00066" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00067 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00067" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00068 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00068" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00070 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00070" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00072 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00072" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00073 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00073" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00074 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00074" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00076 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00076" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00080 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00080" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00082 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00082" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00083 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00083" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8
docker run --network host --name flsim-worker-00086 -d -v /tmp/paper-code-flsim-testbed:/var/app -e TZ=Asia/Shanghai --env NODE_TYPE="node-type-000" --env RUNNER_NAME="flsim-worker-00086" --cpus="2" --memory="6G" docker.flsim.iovi.com:5000/flsim-node:0.2.8