# 基于镜像基础
FROM nikolaik/python-nodejs:python3.7-nodejs18

COPY requirements.txt /var/app/

# 工作目录 /var/app
WORKDIR /var/app

# RUN apt-get update
# RUN apt install -y curl python3

RUN apt-get update
RUN apt-get -y install cron

#RUN curl -sL https://deb.nodesource.com/setup_18.x | bash - 
#RUN apt install -y nodejs

RUN pip install --upgrade pip
RUN pip install -r /var/app/requirements.txt -i https://pypi.mirrors.ustc.edu.cn/simple

#RUN sed -i "s@http://deb.debian.org@http://mirrors.aliyun.com@g" /etc/apt/sources.list
#RUN cat /etc/apt/sources.list
#RUN rm -Rf /var/lib/apt/lists/*

RUN npm install -g nodemon
